# Generated by Django 4.0.4 on 2022-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
